### ISSUE TITLE
Password disclosed

### ISSUE THREAD

**Issue by RicterZ** [Mother-Ship/cabbageWeb#6]
MySQL Password:
https://github.com/Mother-Ship/cabbageWeb/blob/bb53d9ec2436cfdf98f73a2adca79db905a0b810/src/main/resources/generatorConfig.xml#L21 

Mail Password:
https://github.com/Mother-Ship/cabbageWeb/blob/bb53d9ec2436cfdf98f73a2adca79db905a0b810/src/main/resources/mail.properties#L4

**Comment by Mother-Ship** [comment]
十分感谢！ 我只留意到了properties里的数据库密码，没注意生成器配置的。。
邮箱的code倒是早废弃了。。
